version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      
  Server_Testing:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          app-dir: ./server
      - run:
          command: npm install
          working_directory: ./server
      - run:
          command: npm test
          working_directory: ./server
            
  Client_Testing:
    executor:
      name: node/default
    steps:
      - run:
          command: npm install
          working_directory: ./client
      - run:
          command: npm test
          working_directory: ./client
workflows:
    build-and-test:
      jobs:
        - build-and-test
        - build
        - Server-Testing:
            requires:
              - build
        - Client-Testing:
            requires:
              - build
